services:
  idp:
    build:
      context: ./idp
      dockerfile: Dockerfile
    volumes:
      - ./idp:/app
    ports:
      - "8080:8080"

  sp:
    build:
      context: ./sp
      dockerfile: Dockerfile
    volumes:
      - ./sp:/app
    ports:
      - "8081:8081"
